export const PAGE_PRIMARY_COLOR = "#00305C"; //blue color
export const PAGE_SECONDARY_COLOR = "#FFFFFF"; //white color
export const PAGE_PRIMARY_COLOR_DARK = "#176aaa";
export const AUTH_ACTIVE_TAB_COLOR = "rgb(24 69 112)";
export const AUTH_PASSIVE_TAB_COLOR = "#FFFFFF";
export const AUTH_ACTIVE_TAB_TEXT_COLOR = "#FFFFFF";
export const AUTH_PASSIVE_TAB_TEXT_COLOR = "rgb(24 69 112)";
export const BUY_BTN_COLOR = "rgb(220, 36, 36)";
export const BUY_BTN_DARK_COLOR = "#d40404";
export const ADD_TO_CART_BTN_COLOR = "#FF00B5";
export const ADD_TO_CART_BTN_DARK_COLOR = "#DE00B5";
export const EDIT_BTN_COLOR = "#009D00";
export const EDIT_BTN_DARK_COLOR = "#007A00";
export const DELETE_BTN_COLOR = "#7D0000";
export const DELETE_BTN_DARK_COLOR = "#650000";
